/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MRouteImport } from './routes/m'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as MYieldRouteImport } from './routes/m.yield'
import { Route as MWishlistRouteImport } from './routes/m.wishlist'
import { Route as MSimulatorRouteImport } from './routes/m.simulator'
import { Route as MSettingsRouteImport } from './routes/m.settings'
import { Route as MGoalsRouteImport } from './routes/m.goals'
import { Route as MBondRouteImport } from './routes/m.bond'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppYieldRouteImport } from './routes/app.yield'
import { Route as AppWishlistRouteImport } from './routes/app.wishlist'
import { Route as AppSimulatorRouteImport } from './routes/app.simulator'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppBondRouteImport } from './routes/app.bond'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MYieldRoute = MYieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => MRoute,
} as any)
const MWishlistRoute = MWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => MRoute,
} as any)
const MSimulatorRoute = MSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => MRoute,
} as any)
const MSettingsRoute = MSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MRoute,
} as any)
const MGoalsRoute = MGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => MRoute,
} as any)
const MBondRoute = MBondRouteImport.update({
  id: '/bond',
  path: '/bond',
  getParentRoute: () => MRoute,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYieldRoute = AppYieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => AppRoute,
} as any)
const AppWishlistRoute = AppWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppBondRoute = AppBondRouteImport.update({
  id: '/bond',
  path: '/bond',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/developers': typeof DevelopersRoute
  '/m': typeof MRouteWithChildren
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/resources': typeof ResourcesRoute
  '/app/bond': typeof AppBondRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/app/yield': typeof AppYieldRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/m/bond': typeof MBondRoute
  '/m/goals': typeof MGoalsRoute
  '/m/settings': typeof MSettingsRoute
  '/m/simulator': typeof MSimulatorRoute
  '/m/wishlist': typeof MWishlistRoute
  '/m/yield': typeof MYieldRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/m/': typeof MIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/developers': typeof DevelopersRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/resources': typeof ResourcesRoute
  '/app/bond': typeof AppBondRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/app/yield': typeof AppYieldRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/m/bond': typeof MBondRoute
  '/m/goals': typeof MGoalsRoute
  '/m/settings': typeof MSettingsRoute
  '/m/simulator': typeof MSimulatorRoute
  '/m/wishlist': typeof MWishlistRoute
  '/m/yield': typeof MYieldRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/careers': typeof CareersIndexRoute
  '/m': typeof MIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/developers': typeof DevelopersRoute
  '/m': typeof MRouteWithChildren
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/resources': typeof ResourcesRoute
  '/app/bond': typeof AppBondRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/app/yield': typeof AppYieldRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/m/bond': typeof MBondRoute
  '/m/goals': typeof MGoalsRoute
  '/m/settings': typeof MSettingsRoute
  '/m/simulator': typeof MSimulatorRoute
  '/m/wishlist': typeof MWishlistRoute
  '/m/yield': typeof MYieldRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/m/': typeof MIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/company'
    | '/developers'
    | '/m'
    | '/partners'
    | '/pricing'
    | '/products'
    | '/resources'
    | '/app/bond'
    | '/app/goals'
    | '/app/marketplace'
    | '/app/onboarding'
    | '/app/settings'
    | '/app/simulator'
    | '/app/wishlist'
    | '/app/yield'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/m/bond'
    | '/m/goals'
    | '/m/settings'
    | '/m/simulator'
    | '/m/wishlist'
    | '/m/yield'
    | '/app/'
    | '/blog/'
    | '/careers/'
    | '/m/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/company'
    | '/developers'
    | '/partners'
    | '/pricing'
    | '/products'
    | '/resources'
    | '/app/bond'
    | '/app/goals'
    | '/app/marketplace'
    | '/app/onboarding'
    | '/app/settings'
    | '/app/simulator'
    | '/app/wishlist'
    | '/app/yield'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/m/bond'
    | '/m/goals'
    | '/m/settings'
    | '/m/simulator'
    | '/m/wishlist'
    | '/m/yield'
    | '/app'
    | '/blog'
    | '/careers'
    | '/m'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/company'
    | '/developers'
    | '/m'
    | '/partners'
    | '/pricing'
    | '/products'
    | '/resources'
    | '/app/bond'
    | '/app/goals'
    | '/app/marketplace'
    | '/app/onboarding'
    | '/app/settings'
    | '/app/simulator'
    | '/app/wishlist'
    | '/app/yield'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/m/bond'
    | '/m/goals'
    | '/m/settings'
    | '/m/simulator'
    | '/m/wishlist'
    | '/m/yield'
    | '/app/'
    | '/blog/'
    | '/careers/'
    | '/m/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompanyRoute: typeof CompanyRoute
  DevelopersRoute: typeof DevelopersRoute
  MRoute: typeof MRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  ResourcesRoute: typeof ResourcesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CareersSlugRoute: typeof CareersSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/m/yield': {
      id: '/m/yield'
      path: '/yield'
      fullPath: '/m/yield'
      preLoaderRoute: typeof MYieldRouteImport
      parentRoute: typeof MRoute
    }
    '/m/wishlist': {
      id: '/m/wishlist'
      path: '/wishlist'
      fullPath: '/m/wishlist'
      preLoaderRoute: typeof MWishlistRouteImport
      parentRoute: typeof MRoute
    }
    '/m/simulator': {
      id: '/m/simulator'
      path: '/simulator'
      fullPath: '/m/simulator'
      preLoaderRoute: typeof MSimulatorRouteImport
      parentRoute: typeof MRoute
    }
    '/m/settings': {
      id: '/m/settings'
      path: '/settings'
      fullPath: '/m/settings'
      preLoaderRoute: typeof MSettingsRouteImport
      parentRoute: typeof MRoute
    }
    '/m/goals': {
      id: '/m/goals'
      path: '/goals'
      fullPath: '/m/goals'
      preLoaderRoute: typeof MGoalsRouteImport
      parentRoute: typeof MRoute
    }
    '/m/bond': {
      id: '/m/bond'
      path: '/bond'
      fullPath: '/m/bond'
      preLoaderRoute: typeof MBondRouteImport
      parentRoute: typeof MRoute
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/yield': {
      id: '/app/yield'
      path: '/yield'
      fullPath: '/app/yield'
      preLoaderRoute: typeof AppYieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wishlist': {
      id: '/app/wishlist'
      path: '/wishlist'
      fullPath: '/app/wishlist'
      preLoaderRoute: typeof AppWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulator': {
      id: '/app/simulator'
      path: '/simulator'
      fullPath: '/app/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bond': {
      id: '/app/bond'
      path: '/bond'
      fullPath: '/app/bond'
      preLoaderRoute: typeof AppBondRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBondRoute: typeof AppBondRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppWishlistRoute: typeof AppWishlistRoute
  AppYieldRoute: typeof AppYieldRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBondRoute: AppBondRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppWishlistRoute: AppWishlistRoute,
  AppYieldRoute: AppYieldRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MRouteChildren {
  MBondRoute: typeof MBondRoute
  MGoalsRoute: typeof MGoalsRoute
  MSettingsRoute: typeof MSettingsRoute
  MSimulatorRoute: typeof MSimulatorRoute
  MWishlistRoute: typeof MWishlistRoute
  MYieldRoute: typeof MYieldRoute
  MIndexRoute: typeof MIndexRoute
}

const MRouteChildren: MRouteChildren = {
  MBondRoute: MBondRoute,
  MGoalsRoute: MGoalsRoute,
  MSettingsRoute: MSettingsRoute,
  MSimulatorRoute: MSimulatorRoute,
  MWishlistRoute: MWishlistRoute,
  MYieldRoute: MYieldRoute,
  MIndexRoute: MIndexRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CompanyRoute: CompanyRoute,
  DevelopersRoute: DevelopersRoute,
  MRoute: MRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  ResourcesRoute: ResourcesRoute,
  BlogSlugRoute: BlogSlugRoute,
  CareersSlugRoute: CareersSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
