// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function trimEnv(v: string | undefined): string | undefined {
  if (v == null) return undefined;
  const t = v.trim();
  return t === "" ? undefined : t;
}

function createSupabaseClient() {
  // IMPORTANT: use static `process.env.NEXT_PUBLIC_*` identifiers only.
  // Dynamic `process.env[key]` is NOT inlined into the browser bundle, so client-side reads fail in dev/prod.
  const SUPABASE_URL =
    trimEnv(process.env.NEXT_PUBLIC_SUPABASE_URL) ||
    trimEnv(process.env.SUPABASE_URL) ||
    trimEnv(process.env.VITE_SUPABASE_URL);
  const SUPABASE_PUBLISHABLE_KEY =
    trimEnv(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) ||
    trimEnv(process.env.SUPABASE_PUBLISHABLE_KEY) ||
    trimEnv(process.env.VITE_SUPABASE_PUBLISHABLE_KEY);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY " +
        "(or SUPABASE_* / VITE_*) in .env at the project root, then restart the dev server. " +
        "If you use `next build` / production hosting, those NEXT_PUBLIC_* vars must be present at build time too.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

